'use strict';

module.exports = {
    en: require('./en'),
    ar: require('./ar'),
    ca: require('./ca'),      
    cz: require('./cz'),
    de: require('./de'),
    es: require('./es'),
    fr: require('./fr'),
    hu: require('./hu'),
    it: require('./it'),
    ja: require('./ja'),
    ko: require('./ko'),
    nb: require('./nb'),
    nl: require('./nl'),
    pl: require('./pl'),
    'pt-BR': require('./pt-BR'),
    ru: require('./ru'),
    sk: require('./sk'),
    sv: require('./sv'),
    th: require('./th'),
    zh: require('./zh'),
    'zh-TW': require('./zh-TW'),
};
